title: "The Heart of Football"
email: "wangzhishan50@gmail.com"
description: "The Heart of Football: Beyond Results, Into Structure, Through the Lens of Control."
baseurl: "/heart-of-football"
url: "https://niconiconi1234567.github.io"
logo: "/assets/images/logo.png"
language: "en"
timezone: "America/New_York"
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
collections:
  writings:
    output: true
    permalink: /writings/:name/
  notes:
    output: true
    permalink: /match-notes/:name/
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: writings
    values:
      layout: writing
      toc: true
  - scope:
      path: ""
      type: notes
    values:
      layout: note
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
